version: "2"
linters:
  default: none
  enable:
    - copyloopvar
    - depguard
    - errcheck
    - funlen
    - goconst
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - wastedassign
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: encoding/json
              desc: use "github.com/bytedance/sonic" instead
            - pkg: io/ioutil
              desc: The io/ioutil package has been deprecated, see https://go.dev/doc/go1.16#ioutil
            - pkg: github.com/stretchr/testify/assert
              desc: Use "gotest.tools/v3/assert" instead
            - pkg: github.com/stretchr/testify/require
              desc: Use "gotest.tools/v3/assert" instead
            - pkg: github.com/stretchr/testify/suite
              desc: Do not use
            - pkg: github.com/tonistiigi/fsutil
              desc: The fsutil module does not have a stable API, so we should not have a direct dependency unless necessary.
    dupl:
      threshold: 100
    funlen:
      lines: 150
      statements: 80
    goconst:
      min-len: 2
      min-occurrences: 2
    gocyclo:
      min-complexity: 50
    govet:
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    lll:
      line-length: 160
      tab-width: 1
    misspell:
      locale: US
    revive:
      confidence: 0.8
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
