version: '3.8'

services:
  app:
    image: myimage:latest
    build:
      context: ../
      dockerfile: Dockerfile.alpine
      # dockerfile: Dockerfile.busybox
      # dockerfile: Dockerfile.debian
    ports:
      - "8000:8000"
      - "8443:8443"
    environment:
      - ENV_VAR_NAME=value
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: