// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.1
// source: ping_service.proto

package ping

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_ping_service_proto protoreflect.FileDescriptor

const file_ping_service_proto_rawDesc = "" +
	"\n" +
	"\x12ping_service.proto\x12\x04ping\x1a\x12ping_request.proto\x1a\x13ping_response.proto2<\n" +
	"\vPingService\x12-\n" +
	"\x04Ping\x12\x11.ping.PingRequest\x1a\x12.ping.PingResponseB\bZ\x06./pingb\x06proto3"

var file_ping_service_proto_goTypes = []any{
	(*PingRequest)(nil),  // 0: ping.PingRequest
	(*PingResponse)(nil), // 1: ping.PingResponse
}
var file_ping_service_proto_depIdxs = []int32{
	0, // 0: ping.PingService.Ping:input_type -> ping.PingRequest
	1, // 1: ping.PingService.Ping:output_type -> ping.PingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ping_service_proto_init() }
func file_ping_service_proto_init() {
	if File_ping_service_proto != nil {
		return
	}
	file_ping_request_proto_init()
	file_ping_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ping_service_proto_rawDesc), len(file_ping_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ping_service_proto_goTypes,
		DependencyIndexes: file_ping_service_proto_depIdxs,
	}.Build()
	File_ping_service_proto = out.File
	file_ping_service_proto_goTypes = nil
	file_ping_service_proto_depIdxs = nil
}
